apiVersion: v1
kind: Service
metadata:
  name: {{ include "skypilot.fullname" . }}-api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP  # Use clusterIP to allow ingress to authenticate
  ports:
    - port: 80
      targetPort: 46580  # Assuming your container listens on port 46580
      protocol: TCP
  selector:
    app: {{ include "skypilot.fullname" . }}-api
    skypilot.co/ready: "true"
