{{- if and (not .Values.ingress.authSecret) .Values.ingress.authCredentials (not .Values.apiService.enableUserManagement) (not (index .Values.ingress "oauth2-proxy" "enabled")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skypilot.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth: {{ .Values.ingress.authCredentials | quote }}
{{- end }}
