{{- if and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
    grafana_datasource: "true"
    tier: skypilot
    component: skypilot-datasource-cm
    {{- with .Values.global.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ .Release.Name }}-prometheus-server:80
        editable: false
        uid: prometheus
        access: proxy
{{- end }}
