{{- if or .Values.apiService.dbConnectionSecretName .Values.apiService.dbConnectionString }}
{{- if .Values.apiService.config }}
{{- fail "When using database connection, .Values.apiService.config must be null.\nDeploy the API server with null config and add the config via the dashboard." }}
{{- end }}

{{- if .Values.apiService.dbConnectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-connection
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection_string: {{ .Values.apiService.dbConnectionString }}
{{- end }}
{{- end }}
