{{- if .Values.prometheus.enabled}}
{{- $fullName := include "skypilot.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-dcgm-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $fullName }}-dcgm-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9400"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: {{ $fullName }}-dcgm-exporter
  ports:
  - name: metrics
    port: 9400
    targetPort: 9400
    protocol: TCP
  type: ClusterIP
{{- end}}
