{{- if or .Values.auth.oauth.enabled (and .Values.ingress.enabled (index .Values.ingress "oauth2-proxy" "enabled")) }}
{{- $fullName := include "skypilot.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $fullName }}-oauth2-proxy
    skypilot.co/component: oauth2-proxy
  name: {{ $fullName }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: {{ $fullName }}-oauth2-proxy
{{- end }}
