# Creates a deployment YAML that runs multiple load balancer replicas and a service to expose them.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-lb-ha-deployment
  labels:
    app: sky-lb-ha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sky-lb-ha
  template:
    metadata:
      labels:
        app: sky-lb-ha
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - sky-lb-ha
                topologyKey: kubernetes.io/hostname
      containers:
      - name: sky-lb-ha
        image: {{docker_image_path}}
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - |
            echo "Controller URL: {{controller_endpoint}}"
            python -m sky.serve.load_balancer --controller-addr {{controller_endpoint}} --load-balancer-port 8890
        ports:
        - containerPort: 8890
        readinessProbe:
          exec:
            command:
              - python
              - -c
              - "import http.client; conn = http.client.HTTPConnection('localhost', 8890); conn.request('GET', '/'); response = conn.getresponse(); import sys; sys.exit(0 if response.status == 307 else 1)"
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Create a service to expose the load balancer
apiVersion: v1
kind: Service
metadata:
  name: sky-lb-ha-service
  labels:
    app: skypilot-lb
spec:
  selector:
    app: sky-lb-ha
  ports:
  - protocol: TCP
    port: 8890
    targetPort: 8890
  type: ClusterIP
---
# Create an ingress rule
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: sky-lb-ha-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /sky-lb-ha(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sky-lb-ha-service
            port:
              number: 8890
